# Site settings
title: Vinícius Almeida
email: vinialm88@gmail.com
description: "Consultor/Programador na CodeMiner24. Interessado em OpenSource e computação em geral."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: vimoding
github_username:  viniciusalmeida
sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
permalink: pretty
