# Site settings
title: Vinícius Almeida
email: vinialm88@gmail.com
description: "Consultor/Programador na CodeMiner42. Interessado em OpenSource, padrões web e computação em geral."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: vimoding
github_username:  viniciusalmeida
sass:
  sass_dir: _sass

# Build settings
markdown: redcarpet
permalink: pretty
